limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;

user  root;
worker_processes 1;

events {
}

http {
    server {
        listen 80;
        server_name _;

        client_max_body_size 20M;

        proxy_read_timeout 60s;
        proxy_connect_timeout 5s;

        gzip on;
        gzip_types text/css application/json application/javascript;

        location /static/ { alias /app/staticfiles/; }
        location /media/  { alias /app/media/; }

        location /api/ {
            limit_req zone=api burst=20 nodelay;
            proxy_pass http://web:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://web:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}