# Generated by Django 6.0.7 on 2026-07-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
