# Generated by Django 6.0.7 on 2026-08-27 19:39

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_views"),
        ("enrollment", "0003_certificate_updated_at_enrollment_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["status", "price"], name="course_status_price_index"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["status", "-created_at"], name="course_status_-created_at_index"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["status", "views"], name="course_status_views_index"
            ),
        ),
    ]
