# Generated by Django 6.1 on 2026-08-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='course_status_price_i',
            old_name='course_status_price_index',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='course_status_-created_at_i',
            old_name='course_status_-created_at_index',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='course_status_views_i',
            old_name='course_status_views_index',
        ),
    ]
