# Generated by Django 6.0.7 on 2026-08-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
