# Generated by Django 6.1 on 2026-08-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_author_amount_payment_commission_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('paid', 'Оплачен'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('earning', 'Начисление'), ('payout', 'Выплата'), ('refund', 'Возврат'), ('adjustment', 'Корректировка')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_entries', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_entries', to='payment.payment')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_entries', to='payment.payout')),
            ],
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['author', 'status'], name='payment_pay_author__d9a763_idx'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_amount_greater_than_zero'),
        ),
        migrations.AddIndex(
            model_name='balanceentry',
            index=models.Index(fields=['author', 'created_at'], name='payment_bal_author__353c9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='balanceentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'earning')), fields=('payment',), name='uniq_earning_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='balanceentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'payout')), fields=('payout',), name='uniq_payout_per_payout'),
        ),
    ]
