# Generated by Django 6.1 on 2026-08-31 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paymentmethod_payout_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CARD', 'Банковская карта'), ('SBP', 'По номеру телефона')], max_length=20)),
                ('token', models.CharField(max_length=255)),
                ('masked', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='paymentmethod',
            name='payment_pay_author__52a547_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentmethod',
            name='payment_pay_author__893e60_idx',
        ),
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_payment_is_default',
        ),
        migrations.AddField(
            model_name='payoutmethod',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payout',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payment.payoutmethod'),
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='author',
        ),
        migrations.AddIndex(
            model_name='payoutmethod',
            index=models.Index(fields=['author', 'is_active'], name='payment_pay_author__0b7974_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('author',), name='unique_payout_is_default'),
        ),
        migrations.AddConstraint(
            model_name='payoutmethod',
            constraint=models.UniqueConstraint(fields=('author', 'token'), name='unique_payout_method_token'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
