# Generated by Django 6.0.7 on 2026-08-27 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
