name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: pip install ruff
      - run: ruff check .
      - run: ruff format --check .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Копируем .env
        run: cp .env.ci .env
      - name: Поднимаем redis и rabbitmq
        run: docker compose up -d db redis rabbitmq
      - name: Поднимаем контейнер и запускаем тесты
        run: docker compose run --rm web pytest -v
      - name: Опускаем контейнер
        run: docker compose down -v
        if: always()